blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: 'mailto:security@gfm.io'
    about: >-
      Please send a GPG-encrypted email to security@gfm.io with the GPG key at
      https://www.gfm.io/gpg/security@gfm.io.asc.
